v2-red:
	tinygo flash -target=pca10040-s132v6 -size=short -tags='v2 red' -opt=2 -serial=none -programmer=cmsis-dap .

v2-blue:
	tinygo flash -target=pca10040-s132v6 -size=short -tags='v2 blue' -opt=2 -serial=none -programmer=cmsis-dap .
