microbit:
	tinygo flash -target=microbit-s110v8 -size=short -opt=2 -programmer=cmsis-dap .

pca10040:
	tinygo flash -target=pca10040-s132v6 -size=short -opt=2 -programmer=cmsis-dap .

v2-red:
	tinygo flash -target=pca10040-s132v6 -size=short -tags='v2 red' -opt=2 -programmer=cmsis-dap .

v2-blue:
	tinygo flash -target=pca10040-s132v6 -size=short -tags='v2 blue' -opt=2 -programmer=cmsis-dap .
